dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.4.1
  # - amicable-alpaca/solidity-stringutils@1.0.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.1'
      # - '@amicable-alpaca=amicable-alpaca/solidity-stringutils@1.0.0'
dotenv: .env
networks:
  default: development
  rinkeby:
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    verify: True
  kovan:
    link_token: '0xa36085F69e2889c224210F603D836748e7dC0088'
    verify: True
  polygon-test:
    verify: True
  avax-test:
    verify: True
  mainnet-fork:
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
  oracle_key: ${ORACLE_KEY}